# version: "3.8"

services:
  django:
    container_name: django
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=fsadfaskldfjm;alsdkjf
      - ALLOWED_HOSTS=localhost,127.0.0.1 

  react:
    container_name: react
    build:
      context: ./frontend
    # command: yarn start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django

#   db:
#     image: postgres:???
#     container_name: postgres
#     volumes:
#     ports:
#     enviroment:

# volumes:
