services:
  stats_service:
    container_name: stats-service
    build:
      context: ./backend/stats_service
    volumes:
      - ./backend/stats_service:/usr/src/app/
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
      - gateway
      - postgres
    networks:
      - backend

  user_service:
    container_name: user-service
    build:
      context: ./backend/user_service
    volumes:
      - ./backend/user_service:/usr/src/app/
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
      - gateway
      - postgres
    networks:
      - backend

  auth_service:
    container_name: auth-service
    build:
      context: ./backend/auth_service
    volumes:
      - ./backend/auth_service:/usr/src/app/
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
      - gateway
      - postgres
    networks:
      - backend

  game_service:
    container_name: game-service
    build:
      context: ./backend/game_service
    volumes:
      - ./backend/game_service:/usr/src/app/
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend

  tournament_service:
    container_name: tournament-service
    build:
      context: ./backend/tournament_service
    volumes:
      - ./backend/tournament_service:/usr/src/app/
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend

  gateway:
    container_name: gateway
    build:
      context: ./backend/gateway
    volumes:
      - ./backend/gateway:/usr/src/app/
    env_file:
      - ./backend/.env
    networks:
      - transcendence
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./elk_stack/logs/nginx_logs:/var/log/nginx
    ports:
      - 443:443
    env_file:
      - ./frontend/.env
    depends_on:
      - postgres
    networks:
      - transcendence

  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
    networks:
      - backend

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elk_stack/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
    networks:
      - transcendence
      - backend

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ./elk_stack/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk_stack/logs/nginx_logs:/var/log/nginx
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - transcendence
      - backend

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    depends_on:
      - elasticsearch
    volumes:
      - ./elk_stack/kibana/kibana_index_pattern.ndjson:/usr/share/kibana/config/kibana_index_pattern.ndjson
      - ./elk_stack/kibana/kibana-setup.sh:/usr/local/bin/kibana-setup.sh
      - ./elk_stack/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - transcendence
      - backend
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/kibana-docker && /usr/local/bin/kibana-setup.sh"]

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - transcendence
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - transcendence
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./data/grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - ./data/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./data/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml


  # elasticsearch:
  #   image: elasticsearch:7.16.2
  #   container_name: elasticsearch
  #   restart: always
  #   volumes:
  #     - elastic_data:/usr/share/elasticsearch/data/
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx1g -Xms1g"
  #     discovery.type: single-node
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   networks:
  #     - elk
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 2g

  # logstash:
  #   image: logstash:7.16.2
  #   container_name: logstash
  #   restart: always
  #   volumes:
  #     - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash_dir/logstash.conf
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - '9600:9600'
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx1g -Xms1g"
  #   networks:
  #     - elk
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 2g

  # kibana:
  #   image: kibana:7.16.2
  #   container_name: kibana
  #   restart: always
  #   ports:
  #     - '5601:5601'
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elk
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 2g

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    expose:
      - "5672"
      - "15672"
    env_file:
      - rabbitmq/.env
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - transcendence
      - backend

volumes:
  postgres-data:
  prometheus-data: {}
  grafana-storage: {}
  elastic_data: {}

networks:
  transcendence:
    driver: bridge
  backend:
    driver: bridge