# Generated by Django 4.2.13 on 2024-06-01 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('score', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_service_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('tournament_game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.UUIDField()),
                ('round', models.IntegerField()),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_service_app.tournament')),
            ],
        ),
    ]
