# Generated by Django 4.2.13 on 2024-06-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_service_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
    ]
