# Generated by Django 4.2.2 on 2024-05-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
