# Generated by Django 4.2.2 on 2024-05-30 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAppearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paddle_color', models.TextField(default='#FFF')),
                ('ball_color', models.TextField(default='#FFF')),
                ('background_color', models.TextField(default='#000')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_appearance', to='user_service_app.user')),
            ],
        ),
    ]
